GET http://localhost:3003/posts/df8efafb-b441-49be-ad1b-e76b304703de
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlNzM1NzM5LWUzNmItNDFjNS1hYzI5LWIxODAwODY0ZDcxMyIsImlhdCI6MTYyOTc0MTUyMSwiZXhwIjoxNjI5NzQ1MTIxfQ.TIpPgb_3rw_eW_YntJo6XHNE7QR89laxN3Vjwrubk9k

###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "teste2",
    "email": "bruna23@labenu.com",
    "password": "123456"
}

###
POST https://labook-projeto.herokuapp.com/users/login
Content-Type: application/json

{
    "email": "ana@labenu.com",
    "password": "123456"
}

###
POST http://localhost:3003/posts/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlNzM1NzM5LWUzNmItNDFjNS1hYzI5LWIxODAwODY0ZDcxMyIsImlhdCI6MTYyOTc0MTUyMSwiZXhwIjoxNjI5NzQ1MTIxfQ.TIpPgb_3rw_eW_YntJo6XHNE7QR89laxN3Vjwrubk9k

{
    "photo": "url ana2",
    "description": "post ana3",
    "type": "teste"
}